production:
  url:                    # http://your-domain.tld/request/uri
  ssl_verify_none: false  # true to disable SSL verification

development:
  url:                    # http://your-domain.tld/request/uri
  ssl_verify_none: false  # true to disable SSL verification
